Search.appendIndex(
    [
                {
            "fqsen": "\\MatthiasMullie\\Minify\\Exception",
            "name": "Exception",
            "summary": "Base\u0020Exception\u0020Class.",
            "url": "classes/MatthiasMullie-Minify-Exception.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\Exceptions\\BasicException",
            "name": "BasicException",
            "summary": "Basic\u0020Exception\u0020Class.",
            "url": "classes/MatthiasMullie-Minify-Exceptions-BasicException.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\Exceptions\\FileImportException",
            "name": "FileImportException",
            "summary": "File\u0020Import\u0020Exception\u0020Class.",
            "url": "classes/MatthiasMullie-Minify-Exceptions-FileImportException.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\Exceptions\\IOException",
            "name": "IOException",
            "summary": "IO\u0020Exception\u0020Class.",
            "url": "classes/MatthiasMullie-Minify-Exceptions-IOException.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\JS",
            "name": "JS",
            "summary": "JavaScript\u0020Minifier\u0020Class.",
            "url": "classes/MatthiasMullie-Minify-JS.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\JS\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Init\u0020the\u0020minify\u0020class\u0020\u002D\u0020optionally,\u0020code\u0020may\u0020be\u0020passed\u0020along\u0020already.",
            "url": "classes/MatthiasMullie-Minify-JS.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\JS\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Minify\u0020the\u0020data.",
            "url": "classes/MatthiasMullie-Minify-JS.html#method_execute"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\Minify",
            "name": "Minify",
            "summary": "Abstract\u0020minifier\u0020class.",
            "url": "classes/MatthiasMullie-Minify-Minify.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\Minify\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Init\u0020the\u0020minify\u0020class\u0020\u002D\u0020optionally,\u0020code\u0020may\u0020be\u0020passed\u0020along\u0020already.",
            "url": "classes/MatthiasMullie-Minify-Minify.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\Minify\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Add\u0020a\u0020file\u0020or\u0020straight\u002Dup\u0020code\u0020to\u0020be\u0020minified.",
            "url": "classes/MatthiasMullie-Minify-Minify.html#method_add"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\Minify\u003A\u003AaddFile\u0028\u0029",
            "name": "addFile",
            "summary": "Add\u0020a\u0020file\u0020to\u0020be\u0020minified.",
            "url": "classes/MatthiasMullie-Minify-Minify.html#method_addFile"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\Minify\u003A\u003Aminify\u0028\u0029",
            "name": "minify",
            "summary": "Minify\u0020the\u0020data\u0020\u0026\u0020\u0028optionally\u0029\u0020saves\u0020it\u0020to\u0020a\u0020file.",
            "url": "classes/MatthiasMullie-Minify-Minify.html#method_minify"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\Minify\u003A\u003Agzip\u0028\u0029",
            "name": "gzip",
            "summary": "Minify\u0020\u0026\u0020gzip\u0020the\u0020data\u0020\u0026\u0020\u0028optionally\u0029\u0020saves\u0020it\u0020to\u0020a\u0020file.",
            "url": "classes/MatthiasMullie-Minify-Minify.html#method_gzip"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\Minify\u003A\u003Acache\u0028\u0029",
            "name": "cache",
            "summary": "Minify\u0020the\u0020data\u0020\u0026\u0020write\u0020it\u0020to\u0020a\u0020CacheItemInterface\u0020object.",
            "url": "classes/MatthiasMullie-Minify-Minify.html#method_cache"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\Minify\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Minify\u0020the\u0020data.",
            "url": "classes/MatthiasMullie-Minify-Minify.html#method_execute"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify",
            "name": "Minify",
            "summary": "",
            "url": "namespaces/matthiasmullie-minify.html"
        },                {
            "fqsen": "\\MatthiasMullie",
            "name": "MatthiasMullie",
            "summary": "",
            "url": "namespaces/matthiasmullie.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Minify\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/matthiasmullie-minify-exceptions.html"
        }            ]
);
